# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Tomas Jochym-O'Connor
title_html: "<b>Tomas Jochym-O'Connor</b>"
email: your-email@example.com
# pitch: This is a pitch.
description: >- # this means to ignore newlines until "baseurl:"
  Physicist, quantum information theorist, and post-doctoral fellow at Caltech.
baseurl: "tjoc" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:
linkedin_username: tjochymoconnor
scholar_username: user=eZhvZL4AAAAJ&hl=en
arxiv_username: Jochym-O%27Connor%2C+T

#author_display: true
#curriculum:
  #name: CV
  #url: cv.pdf
#shortbio: This is my short bio

# Build settings
markdown: kramdown
theme: academic
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
